#!/usr/bin/env bash
set -euo pipefail

if [ "$(uname)" == 'Linux' ]; then
  # https://github.com/multiarch/qemu-user-static
  docker run --rm --privileged multiarch/qemu-user-static@sha256:28ebe2e48220ae8fd5d04bb2c847293b24d7fbfad84f0b970246e0a4efd48ad6 --reset -p yes
fi
