#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

test -n "$VERSION" || (echo 'VERSION env variable must be set' >&2; exit 1)

./mvnw -pl ice-rest-catalog validate # fail-fast

image_name=altinity/ice-rest-catalog

# TODO: s/latest/nonroot
for q in "" "debug-"; do
  base_image_prefix="$q"
  if [[ "$q" == "" ]]; then
    base_image_prefix="latest-"
  fi
  docker build --platform linux/amd64 --build-arg "BASE_IMAGE_TAG=${base_image_prefix}amd64" --build-arg "VERSION=$VERSION" -t "$image_name:$q$VERSION-amd64" -f ice-rest-catalog/Dockerfile .
  docker build --platform linux/arm64 --build-arg "BASE_IMAGE_TAG=${base_image_prefix}arm64" --build-arg "VERSION=$VERSION" -t "$image_name:$q$VERSION-arm64" -f ice-rest-catalog/Dockerfile .
done

docker build --platform linux/amd64 --build-arg "BASE_IMAGE_TAG=debug-amd64" --build-arg "VERSION=$VERSION" --build-arg "ICE_IMAGE_TAG=$VERSION-amd64" -t "$image_name:debug-with-ice-$VERSION-amd64" -f ice-rest-catalog/Dockerfile.with-ice .
docker build --platform linux/arm64 --build-arg "BASE_IMAGE_TAG=debug-arm64" --build-arg "VERSION=$VERSION" --build-arg "ICE_IMAGE_TAG=$VERSION-arm64" -t "$image_name:debug-with-ice-$VERSION-arm64" -f ice-rest-catalog/Dockerfile.with-ice .

push=false
for arg in "$@"; do
  if [[ "$arg" == "--push" ]]; then
    push=true
    break
  fi
done
if ! $push; then
  echo >&2 'Skipping docker push (--push not set)'
  exit 0
fi

for q in "" "debug-" "debug-with-ice-"; do
  docker push "$image_name:$q$VERSION-amd64"
  docker push "$image_name:$q$VERSION-arm64"
  # `docker manifest` requires metadata from the registry, hence the `docker push`es above
  docker manifest create "$image_name:$q$VERSION" \
    --amend "$image_name:$q$VERSION-amd64" \
    --amend "$image_name:$q$VERSION-arm64"
  docker manifest push "$image_name:$q$VERSION"
done

regctl image copy "$image_name:$VERSION" "$image_name:latest"
regctl image copy "$image_name:debug-$VERSION" "$image_name:debug"
regctl image copy "$image_name:debug-with-ice-$VERSION" "$image_name:debug-with-ice"
