#!/usr/bin/env bash
set -euo pipefail
DIR="$(dirname "${BASH_SOURCE[0]}")/.."
exec_args=""
for arg in "$@"; do
  exec_args+=("'${arg//\'/\'\\\'\'}'")
done
exec_args=$(IFS=" "; echo "${exec_args[*]}")
exec "$DIR/mvnw" -f "$DIR/pom.xml" -q -Pno-check -am -pl ice compile exec:java -Dexec.mainClass=com.altinity.ice.cli.Main -Dexec.args="$exec_args"
