#!/usr/bin/env bash
set -euo pipefail
DIR="$(dirname "${BASH_SOURCE[0]}")/.."
exec "$DIR/mvnw" -f "$DIR/pom.xml" -q -Pno-check -pl ice-rest-catalog compile exec:java -Dexec.mainClass=com.altinity.ice.rest.catalog.Main -Dexec.args="$*" # FIXME: $*
