#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

test -n "$VERSION" || (echo 'VERSION env variable must be set' >&2; exit 1)

./mvnw clean verify

rm -f release

_undo_mvn_version_set() {
  ./mvnw versions:revert
}
trap _undo_mvn_version_set EXIT
./mvnw versions:set -DnewVersion=$VERSION

./mvnw clean package -Dmaven.test.skip=true
_undo_mvn_version_set

docker-build-ice
docker-build-ice-rest-catalog

render-github-release-template
# TODO: sign

push=false
for arg in "$@"; do
  if [[ "$arg" == "--push" ]]; then
    push=true
    break
  fi
done
if ! $push; then
  echo >&2 'Skipping release push (--push not set)'
  exit 0
fi

github-release delete --user altinity --repo ice --tag "$VERSION_TAG" || true

cat release/GITHUB_RELEASE.md | github-release release \
  --target "master" --user "altinity" --repo "ice" --tag "$VERSION_TAG" --name "$VERSION" --description -
sleep 7
for f in ice ice-rest-catalog; do
    echo "Uploading $f..." >&2
    github-release upload --user altinity --repo ice --tag "$VERSION_TAG" --name "$f" --file "$f/target/$f-jar"
done

docker-build-ice --push
docker-build-ice-rest-catalog --push
