#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

test -n "$VERSION" || (echo 'VERSION env variable must be set' >&2; exit 1)
test -n "$GITHUB_TOKEN" || (echo 'GITHUB_TOKEN env variable must be set' >&2; exit 1)

./mvnw clean verify

rm -rf release/

_undo_mvn_version_set() {
  ./mvnw versions:revert
}
trap _undo_mvn_version_set EXIT
./mvnw versions:set -DnewVersion=$VERSION

./mvnw clean package -Dmaven.test.skip=true
_undo_mvn_version_set

export PATH="$(pwd)/.bin:$PATH"

echo >&2 'Building ice Docker image'
docker-build-ice
echo >&2 'Building ice-rest-catalog Docker image'
docker-build-ice-rest-catalog

render-github-release-template
# TODO: sign

push=false
for arg in "$@"; do
  if [[ "$arg" == "--push" ]]; then
    push=true
    break
  fi
done
if ! $push; then
  echo >&2 'Skipping release push (--push not set)'
  exit 0
fi

VERSION_TAG="v$VERSION"

# TODO: go install github.com/aktau/github-release@v0.10.0
github-release delete --user altinity --repo ice --tag "$VERSION_TAG" || true
sleep 7
cat release/GITHUB_RELEASE.md | github-release release \
  --target master --user altinity --repo ice --tag "$VERSION_TAG" --name "$VERSION_TAG" --description -
sleep 7
for f in ice ice-rest-catalog; do
    echo "Uploading $f..." >&2
    github-release upload --user altinity --repo ice --tag "$VERSION_TAG" --name "$f-$VERSION" --file "$f/target/$f-jar"
done

echo >&2 'Pushing ice Docker image'
docker-build-ice --push
echo >&2 'Pushing ice-rest-catalog Docker image'
docker-build-ice-rest-catalog --push
