[project]
name = "ice-rest-catalog.pyiceberg-test"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pyarrow>=19.0.1",
    "pyiceberg[pyarrow]>=0.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
