uri: jdbc:sqlite:file:data/ice-rest-catalog/db.sqlite?journal_mode=WAL&synchronous=OFF&journal_size_limit=500

# To use etcd instead of sqlite, start etcd with `etcd --data-dir=data/etcd`, then uncomment the line below
#uri: etcd:http://localhost:2379

warehouse: file://tmp/path/to/warehouse
localFileIOBaseDir: /

#warehouse: s3://bucket1

s3:
  endpoint: http://localhost:9000
  pathStyleAccess: true
  accessKeyID: miniouser
  secretAccessKey: miniopassword
  region: minio

bearerTokens:
- value: foo

anonymousAccess:
  enabled: true
  accessConfig: {}
