#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -a
source "$DIR/minio.env"
set +a

mkdir -p "$DIR/data/mc"

mc --config-dir "$DIR/data/mc" alias set "local" "http://localhost:9000" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" >/dev/null
exec mc --config-dir "$DIR/data/mc" "$@"
