name: release
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: |-
          Version, e.g. 0.1.0.
          Please update CHANGELOG.md before running this workflow.
        required: true
concurrency: release
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
      - name: regctl login
        uses: regclient/actions/regctl-login@main

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: go install github.com/aktau/github-release@v0.10.0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: maven

      - run: .bin/release --push
        env:
          GITHUB_TOKEN: ${{ github.token }}
          VERSION: ${{ github.event.inputs.VERSION }}
